### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Rishi-Mishra0704**
# API BASED WEBAPP

### **_I Rishi Mishra along with my partner @DilsherB made a webapp that takes data from 2 APIs and displays them in a stylish manner_**

**Here are the key features:** 

- Made a homepage that displays movies
- Take movies from tvmaze api 
- Add a like counter 
- Update likes based on the data given by involvement api
- Update api when the like button is clicked
- Add a comment button
- Add a pop up for comment button
- Comment counter is updated based on the number of comments
- Update api when the comment is submitted
- Add tests for item counter and comments
-Add  Basic styling

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
Hello team😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 
- Well done working with the APIs so far on this great app
- Well done writing and testing the counter functions of the comments and movies listed
- Nice work with the comments popup menu, it's well-designed and clean JS logic
- Great job using JS ES6 features as async await
- Nicely designed
- Descriptive PR and Presentation
- Correct Linters

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️

- [ ] Please fill the authors' section properly in your README file
- [ ] Please fix the MIT link for a professional README file

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DilsherB** [comment]
Hi, @MahmoudBakr23 thank you for your kind review. the suggested changes has been applied.
image
image

**Comment by DilsherB** [comment]
@MahmoudBakr23 will you approve it or I have to make another request.

**Review by Davidosky007 — APPROVED** [review]
Hi @Rishi-Mishra0704 @DilsherB 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All tests passed ✔️ 
* No linter errors 👍 
* Good looking design 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
